# Generated by Django 2.2.12 on 2020-09-11 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_models',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('surname', models.CharField(blank=True, max_length=200)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('date', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=200)),
                ('question', models.TextField()),
                ('confirmation', models.BooleanField(null=True)),
            ],
        ),
    ]
