# Generated by Django 3.1.3 on 2020-12-26 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact_models',
            new_name='ContactModels',
        ),
    ]
