# Generated by Django 3.1.3 on 2020-12-30 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20201226_2214'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmodels',
            options={'verbose_name_plural': 'Contact'},
        ),
    ]
