# Generated by Django 3.0.7 on 2020-06-29 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop_models',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_shop', models.CharField(max_length=200)),
                ('date_shop', models.DateTimeField(auto_now=True)),
                ('coment_shop', models.TextField()),
                ('confirmation_buy', models.BooleanField(null=True)),
            ],
        ),
    ]
