# Generated by Django 2.2.12 on 2020-09-18 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop_models',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_product', models.CharField(default='tytuł', max_length=40)),
                ('date_product', models.DateTimeField(auto_now=True)),
                ('description_product', models.TextField()),
                ('confirmation_buy', models.BooleanField(null=True)),
                ('price_product', models.DecimalField(decimal_places=2, default=True, max_digits=20)),
                ('image_product', models.FileField(default='załącz', upload_to='upload/')),
            ],
        ),
    ]
