# Generated by Django 2.2.12 on 2020-09-18 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop_models',
            name='image_product',
            field=models.FileField(default=False, upload_to='upload/'),
        ),
    ]
