# Generated by Django 3.0.7 on 2020-06-29 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop_models',
            name='price',
            field=models.DecimalField(decimal_places=2, default=True, max_digits=500),
        ),
    ]
