# Generated by Django 2.2.12 on 2020-09-18 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20200918_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop_models',
            name='image_product',
            field=models.FileField(default='upload', upload_to='upload/'),
        ),
    ]
