# Generated by Django 2.2.12 on 2020-10-13 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_customer_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingaddress',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
