# Generated by Django 2.2.12 on 2020-09-18 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20200918_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop_models',
            name='title_product',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
