# Generated by Django 2.2.12 on 2020-10-13 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_shoppingaddress_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingaddress',
            name='number',
            field=models.IntegerField(max_length=9, null=True),
        ),
    ]
