# Generated by Django 2.2.12 on 2020-09-23 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20200918_0956'),
    ]

    operations = [
        migrations.CreateModel(
            name='EV_22kW',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_product', models.CharField(max_length=40, null=True)),
                ('date_product', models.DateTimeField(auto_now=True)),
                ('description_product', models.TextField()),
                ('confirmation_buy', models.BooleanField(null=True)),
                ('price_product', models.DecimalField(decimal_places=2, default=True, max_digits=20)),
                ('image_product', models.FileField(null=True, upload_to='upload/')),
            ],
        ),
        migrations.CreateModel(
            name='EV_7kW',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_product', models.CharField(max_length=40, null=True)),
                ('date_product', models.DateTimeField(auto_now=True)),
                ('description_product', models.TextField()),
                ('confirmation_buy', models.BooleanField(null=True)),
                ('price_product', models.DecimalField(decimal_places=2, default=True, max_digits=20)),
                ('image_product', models.FileField(null=True, upload_to='upload/')),
            ],
        ),
        migrations.RenameModel(
            old_name='Shop_models',
            new_name='cable_32A',
        ),
    ]
