# Generated by Django 2.2.12 on 2020-10-13 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_shoppingaddress_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingaddress',
            name='number',
            field=models.IntegerField(null=True),
        ),
    ]
