# Generated by Django 2.2.12 on 2020-09-23 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20200923_0935'),
    ]

    operations = [
        migrations.CreateModel(
            name='PVinverters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_product', models.CharField(max_length=40, null=True)),
                ('date_product', models.DateTimeField(auto_now=True)),
                ('description_product', models.TextField()),
                ('confirmation_buy', models.BooleanField(null=True)),
                ('price_product', models.DecimalField(decimal_places=2, default=True, max_digits=20)),
                ('image_product', models.FileField(null=True, upload_to='upload/')),
            ],
        ),
        migrations.CreateModel(
            name='PVmodules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_product', models.CharField(max_length=40, null=True)),
                ('date_product', models.DateTimeField(auto_now=True)),
                ('description_product', models.TextField()),
                ('confirmation_buy', models.BooleanField(null=True)),
                ('price_product', models.DecimalField(decimal_places=2, default=True, max_digits=20)),
                ('image_product', models.FileField(null=True, upload_to='upload/')),
            ],
        ),
        migrations.CreateModel(
            name='PVothers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_product', models.CharField(max_length=40, null=True)),
                ('date_product', models.DateTimeField(auto_now=True)),
                ('description_product', models.TextField()),
                ('confirmation_buy', models.BooleanField(null=True)),
                ('price_product', models.DecimalField(decimal_places=2, default=True, max_digits=20)),
                ('image_product', models.FileField(null=True, upload_to='upload/')),
            ],
        ),
    ]
