# Generated by Django 2.2.12 on 2020-10-13 14:42

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20201013_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingaddress',
            name='number',
            field=phone_field.models.PhoneField(max_length=31, null=True),
        ),
    ]
