# Generated by Django 2.2.12 on 2020-09-24 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_pvinverters_pvmodules_pvothers'),
    ]

    operations = [
        migrations.AddField(
            model_name='cable_32a',
            name='slug',
            field=models.SlugField(default='1'),
            preserve_default=False,
        ),
    ]
