# Generated by Django 2.2.12 on 2020-09-24 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_remove_cable_32a_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='ev_7kw',
            name='categories_product',
            field=models.CharField(choices=[('E7', 'EV7KW'), ('E2', 'EV22KW'), ('EC', 'EVCABLE'), ('PM', 'PVMODULES'), ('PI', 'PVINVERTERS'), ('PO', 'PVOTHERS')], default='E7', max_length=2),
        ),
    ]
