# Generated by Django 2.2.12 on 2020-10-13 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20201013_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingaddress',
            name='email',
            field=models.EmailField(max_length=200, null=True),
        ),
    ]
