# Generated by Django 2.2.12 on 2020-10-13 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_shoppingaddress_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoppingaddress',
            old_name='adres',
            new_name='street',
        ),
        migrations.AddField(
            model_name='shoppingaddress',
            name='streetnumber',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
