# Generated by Django 2.2.12 on 2020-09-24 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20200924_1351'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EV_7kW',
            new_name='shop_products',
        ),
    ]
