# Generated by Django 2.2.12 on 2020-09-24 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_auto_20200924_1530'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cable_32A',
        ),
        migrations.DeleteModel(
            name='EV_22kW',
        ),
        migrations.DeleteModel(
            name='PVinverters',
        ),
        migrations.DeleteModel(
            name='PVmodules',
        ),
        migrations.DeleteModel(
            name='PVothers',
        ),
    ]
