# Generated by Django 2.2.12 on 2020-10-14 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_auto_20201013_2011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingaddress',
            name='street',
        ),
    ]
