# Generated by Django 2.2.12 on 2020-09-26 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_auto_20200924_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop_products',
            name='search',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
