# Generated by Django 2.2.12 on 2020-10-14 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_remove_shoppingaddress_street'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingaddress',
            name='comment',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
