# Generated by Django 2.2.12 on 2020-09-26 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_shop_products_search'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop_products',
            old_name='search',
            new_name='search_product',
        ),
    ]
