# Generated by Django 2.2.12 on 2020-09-26 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_auto_20200926_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop_products',
            name='search_product',
        ),
    ]
