# Generated by Django 2.2.12 on 2020-09-26 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_remove_shop_products_search_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop_products',
            name='search_product',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
