# Generated by Django 2.2.12 on 2020-09-27 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_shop_products_search_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='search_products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_product', models.CharField(max_length=40, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='shop_products',
            name='search_product',
        ),
    ]
