# Generated by Django 2.2.12 on 2020-09-29 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_auto_20200927_1322'),
    ]

    operations = [
        migrations.DeleteModel(
            name='search_products',
        ),
    ]
