# Generated by Django 2.2.12 on 2020-10-04 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_shop_products_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop_products_cart',
            name='image_cart',
            field=models.FileField(null=True, upload_to='upload/cart/'),
        ),
    ]
